# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim
WORKDIR /app

# Copy project
COPY . /app

# Install dependencies and project
RUN pip install --no-cache-dir hatchling && \
    pip install --no-cache-dir .

# Entry point
ENTRYPOINT ["yop-mcp"]
